DROP TABLE IF EXISTS `log`.`logs`;
CREATE TABLE  `log`.`logs` (
  `DATED` varchar(50) default NULL,
  `LOGGER` varchar(1000) default NULL,
  `LEVEL` varchar(10) default NULL,
  `MESSAGE` mediumtext
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS `log`.`kettle_logs`;


CREATE TABLE `log`.`kettle_logs`
(
  ID_JOB INT
, CHANNEL_ID VARCHAR(255)
, JOBNAME VARCHAR(255)
, STATUS VARCHAR(15)
, LINES_READ BIGINT
, LINES_WRITTEN BIGINT
, LINES_UPDATED BIGINT
, LINES_INPUT BIGINT
, LINES_OUTPUT BIGINT
, LINES_REJECTED BIGINT
, ERRORS BIGINT
, STARTDATE DATETIME
, ENDDATE DATETIME
, LOGDATE DATETIME
, DEPDATE DATETIME
, REPLAYDATE DATETIME
, LOG_FIELD MEDIUMTEXT
)ENGINE=InnoDB DEFAULT CHARSET=latin1;